// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'config/app_config.dart';

/// `FlutterFire` configuration for Android.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Lee credenciales del .env a través de AppConfig (protegido por .gitignore)
    return FirebaseOptions(
      apiKey: AppConfig.firebaseApiKey,
      appId: AppConfig.firebaseAppId,
      messagingSenderId: AppConfig.firebaseMessagingSenderId,
      projectId: AppConfig.firebaseProjectId,
      storageBucket: 'horarios-emsa.firebasestorage.app',
      iosBundleId: 'com.example.horariosEmsa',
    );
  }
}
